### ISSUE TITLE
Installing plugins hang..

### ISSUE THREAD

**Issue by QGB** [husixu1/vimrc#1]
卡在这里将近一个小时了，还要等吗。。

1 Installing plugins (35/43)  │1
2   [
  1                             │~
  2 + vim-polyglot: Installing >│~
  3 + vim-devicons: Cloning int>│~
  4 + YCM-Generator: Cloning in>│~
  5 + ultisnips: remote: Compre>│~
  6 + vim-tagbar-css: Cloning i>│~
  7 + vim-snippets: Cloning int>│~
  8 - vim-autotag: remote: Tota>│~
  9 - rainbow_parentheses.vim: >│~
 10 - vim-livedown: remote: Tot>│~
 11 - a.vim: Resolving deltas: >│~
 12 - vinfo: remote: Total 27 (>│~
 13 - nerdtree: Resolving delta>│~
 14 - vimproc: Resolving deltas>│~
 15 - vim-autoformat: remote: T>│~
 16 + syntastic: remote: Compre>│~
 17 - vim-nerdtree-syntax-highl>│~
 18 - DoxygenToolkit.vim: Resol>│~
 19 - tagbar: Resolving deltas:>│~
 20 - undotree: remote: Total 8>│~
 21 - ctrlsf.vim: Resolving del>│~
 22 - tern_for_vim: remote: Tot>│~
 23 - YouCompleteMe: Resolving >│~
 24 - agit.vim: Resolving delta>│~
 25 - vim-minimap: remote: Tota>│~
 26 - vim-merginal: Resolving d>│~
 27 - vim-airline-themes: Resol>│~
 28 - vissort: remote: Total 8 >│~
 29 - vim-nerdtree-tabs: Resolv>│~
 30 - quickr-preview.vim: remot>│~
[Plugins]       2,1          Top [No Name]       0,0-1        All

**Comment by husixu1** [comment]
应该是网络问题，Ctrl-C掉重新PlugInstall就可以了，已经下过的不会丢。vimplug有时候是会有这种问题。（其实用top应该可以看到正在git clone）
